source "https://rubygems.org"

gem "jekyll"
gem "minima"

# Uncomment "github-pages" for GitHub Pages?
#gem "github-pages", group: :jekyll_plugins

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-sitemap"
end

gem "kramdown-parser-gfm"
